// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSRoWt4wyxjZ0LpX5__pW_0l9v4VHIKlM',
    appId: '1:753093451092:web:f785d8c2ed0ffff0e23cc1',
    messagingSenderId: '753093451092',
    projectId: 'agent-ai-calender',
    authDomain: 'agent-ai-calender.firebaseapp.com',
    databaseURL: 'https://agent-ai-calender-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agent-ai-calender.firebasestorage.app',
    measurementId: 'G-E4TVNQS6QY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo5lUvIH_UGhDUvFXkRjqs8yCNbeKPjFs',
    appId: '1:753093451092:android:420509bae684f1e7e23cc1',
    messagingSenderId: '753093451092',
    projectId: 'agent-ai-calender',
    databaseURL: 'https://agent-ai-calender-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agent-ai-calender.firebasestorage.app',
  );
}
